#!/bin/bash
############################################################################# ##
# Copyright (C) 2019-2024 ZKLX Tech, Inc.
############################################################################ ##
#
# -------------------------------------------------------------------------- --
#     AUTHOR                   : EExuke
#     FILE NAME                : preinst.sh
#     FILE DESCRIPTION         : 安装前执行的脚本
#     FIRST CREATION DATE      : 2024/07/30
# --------------------------------------------------------------------------
#     Version                  : 1.0
#     Last Change              : 2024/07/30
## ************************************************************************** ##

#-----------------------------------------------------------
#                CONTROL and COLOUR VARIABLES
#-----------------------------------------------------------
C_ED="\033[0m"    C_HL="\033[01m"   C_UL="\033[04m"
C_BL="\033[05m"   C_RV="\033[07m"   C_HD="\033[08m"
C_UP="\033[nA"    C_DW="\033[nB"    C_RI="\033[nC "
C_LE="\033[nD"    C_PS="\033[y;xH"  C_CL="\033[2J "
F_BL="\033[30m"   F_RD="\033[31m"   F_GR="\033[32m"
F_YL="\033[33m"   F_BU="\033[34m"   F_PU="\033[35m"
F_DG="\033[36m"   F_WT="\033[37m"   B_BL="\033[40m"
B_RE="\033[41m"   B_GR="\033[42m"   B_YL="\033[43m"
B_BU="\033[44m"   B_PR="\033[45m"   B_DG="\033[46m"
B_WT="\033[47m"

#-----------------------------------------------------------
#                  MAIN PROCESS
#-----------------------------------------------------------
echo -e "================================="
echo -e "hello, now is in pre install run:"

# 关闭相关service
echo -e "${F_YL}stop CV services${C_ED}"
sudo systemctl stop ftv_cv.service
sudo systemctl stop ctv_cv.service
sudo systemctl stop itv_cv.service
#sudo systemctl stop citv_cv.service
#sudo systemctl stop fitv_cv.service
echo -e "${F_YL}stop sys services${C_ED}"
sudo systemctl stop ftv_sys.service
sudo systemctl stop ctv_sys.service
sudo systemctl stop itv_sys.service
sudo systemctl stop tv_sys.service
#sudo systemctl stop citv_sys.service
#sudo systemctl stop fitv_sys.service

# 补丁脚本
#echo -e "clear /tmp/patch_root dir"
#sudo rm -rf /tmp/patch_root

echo -e "================================="

